language: node_js
os: linux
dist: xenial
node_js:
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: 14
      deploy:
        provider: npm
        email: rogier+npm@konfirm.eu
        on:
          branch: master
          tags: true
        api_key:
          secure: lWRJXGxn5WQAwaTn9UWr4yoQM5U+WgxwXiHSJ9zCM3oZxrNHPA3oZ1WQL5HwVfBM56doulRHRKXBwsXyJIxni6RxM+7maCC+iwcrvbgUQ3noYubb3i83JcoiUXJgWS/wchzNydntU+HL+66SmIY/B3EAIkmu4aK0FgLVCVN/Ydp4QN4R385CVy3AdtnmvEC6YjezxDAQ+IMQt73VzqpkIRwFsfBKCZ/jFAdS6gztFNzdEzKAdssPaZFfyuDFyJQZKCdD3Nud0BK4ATSKigBnqDRYAFuIOO1ulG53RfD6us2WXQ2cvPFQA+J3Kw7f5XewYUaP3ZyvxDjWt0TR7nXMu6RttxQwfs1q3OoNdt57A+KfYDqg8KjWjTYd1piMsPcL91EkyHam2Z9MgB7ljtxwwPI4mDthKUTzAHQ+IKeyqbGJCqRORzIUnxZepctwmu/+Zu5vGeCimHQPh353PRGj9WFUHwgdBSU+4hbEXJa78qgJdtRg8l+P5EHYdozyFLQhaO4YBlCRX3mVmsb0WnryQUvNKhDxd0BAvUj4S6039+cLZsKpGh42m1WjFdfAhj4lI8eg0jb6ROkfswOuKrTrdcSTpS39dEzRcdNf2I6jYGeGKz7Hvz2aSU195bEU8cxhLQbwOEbpsE7MFVxa7wUso/JuoE6N2418EY/EROf43Z4=
